name: Deploy Next.js SSR app to Azure Web App

on:
  push:
    branches:
      - main # hoặc tên branch bạn dùng để deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 🔧 Install dependencies
        run: npm install

      - name: 🔨 Build Next.js app
        run: npm run build

      - name: 📦 Copy files to deploy folder
        run: |
          mkdir deploy
          cp -r .next public package.json server.js deploy/
          cd deploy && npm install --production

      - name: 🚀 Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "NVS-AM"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B7376F75BED04285ADDDC1100507BB17 }}
          package: ./deploy
