name: Build and deploy Next.js SSR app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Create .env.production
        run: echo "NEXT_PUBLIC_API_BASE_URL=https://nvs.azurewebsites.net/api/v1" > .env.production

      - name: Build project
        run: npm run build

      - name: Zip project for deployment
        run: zip -r build.zip . -x "*.git*" "node_modules/*" "build.zip"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "NVS-AM" # Tên Web App trên Azure
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4F2E52E6CCF3457CAC122A0D41F6EC85 }}
          package: build.zip
